### PR TITLE
LLVM 14 update

### PR DESCRIPTION
**Pull request by jusito**
Because you created already a [pull request](https://github.com/conan-io/conan-center-index/pull/7613) and latest ci failed after components.json.

Fixed it and merged most changes from llvm-core recipe + updated it here and there.
There are still some smaller todos, but recipe is working again, so what do you think?

Edit:
- [x] shared / static are sometimes mixed, for some enabled projects shared / static lib creation seems crossed, e.g. omp.so in static and omp.a in shared build. According to documentation using BUILD_SHARED_LIBS shouldn't be used.
- [x] for shared build all non shared libs are removed, should we add it for static as well?

### CODE REVIEW

**Comment by sykhro** [comment]
I'm interested in this recipe because my workflow relies on libLLVM/libClang.
I have a few notes/questions given that I have made my own version of this:
- if this is intended for libraries, why not use `LLVM_DISTRIBUTION_COMPONENTS`? You can later do `cmake.build(target="install-distribution")` and save yourself some of the work done in `package()`. Personally I'm using the following
```
 tc.cache_variables["LLVM_DISTRIBUTION_COMPONENTS"] = ";".join(
            [
                "cmake-exports",
                "llvm-headers",
                "llvm-libraries",
                "clang-cmake-exports",
                "clang-headers",
                "clang-libraries",
            ]
        )
```
- why is zlib disabled on windows?
- was this tested on windows?

**Comment by jusito** [comment]
1. I didn't know about LLVM_DISTRIBUTION_COMPONENTS, it could indeed be helpful to reduce the size. What do mean by "save yourself some of the work done in package()" ? The main problem in the conan center pr was that the ci is failing, so initial priority was getting one default version into conan center and improve after this point.
2. My priority is linux > mac >>> windows, so I did a test on windows but it wasn't successful as far as I remember. It would be very helpful if you could contribute it.
3. Why is zlib for windows disabled, in short I don't know. Curious why the commit message doesn't indicate it, because I like to commit in small steps. Initial thought "windows build failed because of something around it and I tried llvm-core options"(doesn't look like) or "Deep in llvm cmake/docs there was an exception/mention for it"(doesn't look like) or "zlib for windows didn't work around that time"(no idea). There has to be a reason, but because I cant find it: good finding.

**Comment by sykhro** [comment]
>  What do mean by "save yourself some of the work done in package()"?

You won't have to delete `/share` or /bin`, because they are not there to begin with.

> 2. My priority is linux > mac >>> windows, so I did a test on windows but it wasn't successful as far as I remember. It would be very helpful if you could contribute it.

Gotcha, will check. There's the annoyance of the extension and naming, that is, libLLVMFrontendOpenACC.a is LLVMFrontendOpenACC.lib on Windows.

> 3. Why is zlib for windows disabled, in short I don't know. Curious why the commit message doesn't indicate it, because I like to commit in small steps. Initial thought "windows build failed because of something around it and I tried llvm-core options"(doesn't look like) or "Deep in llvm cmake/docs there was an exception/mention for it"(doesn't look like) or "zlib for windows didn't work around that time"(no idea). There has to be a reason, but because I cant find it: good finding.

It's probably the last point. I have tested it and it seems to work fine...

> The main problem in the conan center pr was that the ci is failing

Yeah this is a bit annoying. For robustness I parse the `llvm.dot` in my recipe with NetworkX, but I imagine that's not an option when making recipes for CCI.

**Comment by jusito** [comment]
> You won't have to delete `/share` or /bin`, because they are not there to begin with.

Ah ok, but at least /bin is not everything cleared, there a regex to indicate what you want to keep.

> Gotcha, will check. There's the annoyance of the extension and naming, that is, libLLVMFrontendOpenACC.a is LLVMFrontendOpenACC.lib on Windows.

Very nice

**Comment by jusito** [comment]
@sykhro Iam currently optimizing the conan2 migration, minimal configuration and most others are looking fine at the end of the day. Do you have time testing it on windows?

**Comment by sykhro** [comment]
> @sykhro Iam currently optimizing the conan2 migration, minimal configuration and most others are looking fine at the end of the day. Do you have time testing it on windows?

Yeah, happy to test whenever you’re ready.
Unfortunately on Windows the DIASDK is needed for PDB generation. We have made a recipe for it so that LLVM doesn’t go fetching it from the visual studio installation, but it’s a bit problematic to fix properly

**Comment by jusito** [comment]
@sykhro merged my latest changes, so I tested llvm 13,14,15,16 in latest patch version in minimal, complete, with dynlib.

edit:
llvm 13,14,15,16 on linux with clang 15
- every with_{project,runtime}=False = minimal configuration
- every with_{project,runtime}=True = complete configuration
  - compiler-rt/libc/lldb seems like they always need some special handling. compiler-rt needs system libs, libc produces a compiler crash, lldb 
- llvm_build_llvm_dylib=True tested and test_package checks for it too
Iam currently looking into libxml2 issues with lldb, tests seem to run whole night but looks good as of now.

So in essence, minimal / minimal+clang / minimal+clang+dynlib would be a good start if that is working fine.
Does it match your preferred configuration?

If you see anything which looks strange or isn't well documented but should be in your opinion, always welcome as feedback.

cheers

**Comment by jusito** [comment]
moved to https://github.com/conan-io/conan-center-index/pull/17509

**Pull request closed without merging**
